# -*- mode: ruby -*-
# vi: set ft=ruby :


$salt_script = <<SALT_SCRIPT

  # Make sure we have its the same in:
  #  - https://github.com/webplatform/ops in vagrant-workbench/Vagrantfile
  #  - https://github.com/webplatform/ops in salt-master/salt-userdata.yml
  ########
  add-apt-repository -y ppa:saltstack/salt
  apt-get update
  apt-get -yqq upgrade
  apt-get -yqq autoremove
  apt-get -yqq install python-dulwich python-git git salt-master salt-minion
  touch /etc/salt/minion.d/id.conf ; grep -q -e "salt" /etc/salt/minion.d/id.conf || printf "id: salt\n" >> /etc/salt/minion.d/id.conf
  ########

  printf "# Workbench" > /etc/salt/minion.d/workbench.conf
  printf "level: workbench\n" > /etc/salt/grains
SALT_SCRIPT


$salt_ip_grain = <<SALT_GRAIN
  echo "Create ~/.ip file so we know the current IP address"
  if [ -f "/etc/salt/pki/master/minions/salt" ]; then
    if [ ! -f "/vagrant/.ip" ]; then
      salt-call --log-level=quiet --no-color --local grains.get ip4_interfaces:eth1 --output=json | python -c 'import sys,json; print json.load(sys.stdin)[\"local\"][0]' > /vagrant/.ip
      #salt-call --log-level=quiet --no-color --local grains.get ipaddr --output=json | python -c 'import sys,json; print json.load(sys.stdin)[\"local\"]' > /vagrant/.ip
      echo " * Created .ip in vagrant-workbench/ folder. You can either edit to match your local environment. If you delete it, it’ll be recreated at next boot."
    else
      echo " * Did not change the .ip file, it already existed."
    fi
  else
    echo " * Could not get the IP, the salt master isnt registered yet."
  fi
SALT_GRAIN


Vagrant.configure(2) do |config|
  config.vm.box = "trusty-cloud"
  config.vm.box_url = "https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box"

  config.vm.network :forwarded_port, host: 4505, guest: 4505
  config.vm.network :forwarded_port, host: 4506, guest: 4506
  config.vm.network :forwarded_port, host: 5353, guest: 5353, protocol: 'udp'
  config.vm.network :forwarded_port, host: 5353, guest: 5353, protocol: 'tcp'

  config.vm.network "private_network", type: "dhcp"

  if Vagrant.has_plugin?("vagrant-cachier")
    # Configure cached packages to be shared between instances of the same base box.
    # More info on http://fgrehm.viewdocs.io/vagrant-cachier/usage
    config.cache.scope = :box

    config.cache.synced_folder_opts = {
      type: :nfs,
      mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
    }
    # ref: http://docs.vagrantup.com/v2/synced-folders/basic_usage.html
  end
  config.cache.enable :apt

  config.vm.hostname =    "salt.workbench.wpdn"
  config.vm.synced_folder "salt/states",    "/srv/local/states"
  config.vm.synced_folder "repos/code",     "/srv/code", create: true
  config.vm.synced_folder "repos/states",   "/srv/salt", create: true
  config.vm.synced_folder "repos/pillar",   "/srv/pillar", create: true
  config.vm.synced_folder "repos/private",  "/srv/private", create: true
  config.vm.synced_folder "repos/runner",   "/srv/runner", create: true
  config.vm.synced_folder "repos/formulas", "/srv/formulas", create: true

  config.vm.provider "virtualbox" do |v|
    v.name = config.vm.hostname
    v.customize ["modifyvm", :id, "--description", "Vagrant Workbench Salt master located in " + File.dirname(__FILE__) ]
    # ref: https://www.virtualbox.org/manual/ch08.html
    #      https://www.virtualbox.org/wiki/Guest_OSes
    v.customize ['modifyvm', :id, '--ostype', 'Ubuntu_64']
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--pae", "on"]
  end

  config.vm.provision :shell, inline: $salt_script

  config.vm.provision :salt do |c|
    c.run_highstate = false
    c.install_master = true
    c.verbose = true
  end

  # Make sure we copy them, because ../salt-master/init.sh normally deletes and its only here that its OK to keep them around.
  config.vm.provision "file", source: ".ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa", run: "always"
  config.vm.provision "file", source: ".ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub", run: "always"

  config.vm.provision "file", source: "../salt-master/init.sh", destination: "/home/vagrant/init.sh"
  config.vm.provision :shell, inline: $salt_ip_grain, run: "always"
end
